"""Regenerate the bundled C++ table from the supplied moderator dataset."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'data/moderators.json').read_text(encoding='utf-8-sig'))
entries = data['moderators']
assert len(entries) == data['counts']['total_entries']
assert len({m['key'] for m in entries}) == len(entries)
lines = ['#pragma once', '// Generated by tools/generate_presets.py; edit data/moderators.json.',
         '#include "reactor_core.hpp"', '#include <string_view>', 'namespace er2 {',
         'struct ModeratorPreset { const char* key; const char* name; const char* type; bool placeable; Moderator material; };',
         'inline constexpr ModeratorPreset moderators[] = {']
for m in entries:
    assert 0 <= m['absorption'] <= 1 and 0 <= m['heat_efficiency'] <= 1
    assert m['moderation'] >= 1 and m['heat_conductivity'] >= 0
    strings = ', '.join(json.dumps(m[k]) for k in ('key', 'name', 'type'))
    values = ', '.join(repr(float(m[k])) for k in ('absorption','heat_efficiency','moderation','heat_conductivity'))
    lines.append(f'    {{{strings}, {str(m["placeable"]).lower()}, {{{values}}}}},')
lines += ['};', 'inline const ModeratorPreset* find_moderator(std::string_view key) {',
          '    for (const auto& m : moderators) if (key == m.key) return &m;', '    return nullptr;', '}', '}']
(root / 'src/moderators.hpp').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Bundled {len(entries)} moderator presets.')
